[tool.ruff]
select = ["ALL"]
ignore = ["ANN101","ANN102","S603"]
[tool.ruff.lint.pydocstyle]
convention = "google"  # Accepts: "google", "numpy", or "pep257".

# Ignore `E402` (import violations) in all `__init__.py`
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
